version: 0.2

env:
  parameter-store:
    NODE_ENV: "davidshefcikcom-api-node-env"
    GITHUB_TOKEN: "davidshefcikcom-api-github-token"
    MONGO_DB: "davidshefcikcom-api-mongodb"
    RECAPTCHA_SECRET_KEY: "davidshefcikcom-api-recaptcha-secret"
    EMAIL: "davidshefcikcom-api-email"

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "Installing node.js."
      - npm install --only=production
  pre_build:
    commands:
      - echo "In the pre build phase."
  build:
    commands:
      - echo "Done with build. Removing old package.json."
  post_build:
    commands:
      - echo "In the post build phase."
      - echo $NODE_ENV
      - echo $GITHUB_TOKEN
      - echo $MONGO_DB
      - echo $RECAPTCHA_SECRET_KEY
      - echo $EMAIL
      
artifacts:
  files:
    - "src/**/*"
    - "node_modules/**/*"
    - "package.json"
  discard-paths: no
